#9 [입력받은 값을 검증하기위한 클래스 생성]
f-lab-edu/HS_ToyJava pull request #14
Opened 2024-09-01 21:34 UTC by rlawltjd8547

2024-09-02 10:28 UTC, f-lab-maverick requested changes
연산하는 부분의 소스코드 복잡도가 높습니다.
로직 파악이 어렵고, 읽기가 어려운 코드가 되었네요.

바로 정답을 알려드리는 것 보다는 이전 기능 개발했던 "숫자야구게임" 에서 소스코드를 어떻게 읽고 관리하기 쉽게 만들었는지 고민해보고 리팩토링해보는건 어떠실까요?

2024-09-02 10:28 UTC, f-lab-maverick commented on Toy2/src/InputParser.java
> +    private final List<String> ParsedResult;
변수명의 첫 글자는 소문자가 컨벤션입니다. 디테일도 신경써주세요~

2024-09-02 10:28 UTC, f-lab-maverick commented on Toy2/src/InputParser.java
> +        }
이 부분의 소스코드 복잡도가 상당히 높습니다.개선할 수 있는 방법은 없을까요?

2024-09-06 08:25 UTC, rlawltjd8547 commented on Toy2/src/InputParser.java
> +        }
그냥 for문이있으면 복잡도 자체가 올라가는것 같습니다
for문을 지워버리고 싶은데 이런 반복적인 행위의 로직구조 자체를
바꾸는 행위는 어떤게 있을지 생각이나지않네요...

2024-09-06 23:04 UTC, f-lab-maverick commented on Toy2/src/InputParser.java
> +        }
정리하기 어렵다면 주석으로 상세하게 동작을 정의해서 동작 파악을 쉽게 만들어주는 방안을 먼저 적용해보세요~

2024-09-14 01:53 UTC, f-lab-maverick approved these changes
고생하셨습니다. 메서드 이름만 수정해주시고 머지해주셔도 좋습니다.

2024-09-14 01:53 UTC, f-lab-maverick commented on Toy2/src/InputParser.java
> +            ParseChar(ch, number);
메서드 이름의 시작은 소문자여야 합니다. 컨벤션에 유의해주세요~

2024-09-14 01:53 UTC, f-lab-maverick commented on Toy2/src/InputParser.java
> +    }
👍

2024-09-19 14:33 UTC, merged