#11 [계산기 메인기능 클래스 생성]
f-lab-edu/HS_ToyJava pull request #18
Opened 2024-09-01 22:08 UTC by rlawltjd8547

1. 사용자의 입력값을 검증하고 파싱해주는 InputParser클래스
 validateState() 는 Calculator 검증메소드인데 2가지 검증의 역할이 다르니깐 필요한건 이해가 가지만
그러면 보통은 기능을 담당하는 클래스가 아닌 하나의 역할을 담당하는 클래스는 검증메소드가 필수일까?...

2. 후위 연산으로 계산을 진행한다

3. 원래는 해당 클래스에서 BigDecimal내부 연산 메소드를 사용하였으나 변경 하였음

4.  validateState() 같은 검증클래스를 따로 빼야할까? CalculatorValidate이런식의 클래스를 따로 생성해야할까

5. isOperator() 이 메소드 다른 클래스에서도 사용되는데 이런 수식들은 상수화? 하듯이 뺄까...

2024-09-02 10:39 UTC, f-lab-maverick requested changes

2024-09-02 10:39 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +        operations.put("%", new Remainder()); // 나머지 연산 추가
note. 이런 연산자는 enum으로 관리한다면 좀 더 깔끔하게 관리할 수 있습니다.
또는 별도  Class로 만들어 관리하실수도 있어요.

ex) `operations.put(Operator.PLUS.key, Operator.PLUS);`

2024-09-02 10:39 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +        }
이건 불필요해보이네요. 이미 파싱이 실패했다면 이전 로직에서 반드시 실패하므로, 해당 로직은 불필요합니다.

2024-09-02 10:39 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +    private void validateState() {
이런 validation을 `InputParser`에서 처리하면 더 좋겠네요. 검증에 대한 책임을 parser에 모두 맡기면 좀 더 집중된 비즈니스 로직이 될 것으로 보입니다. 클래스 / 객체마다 역할과 책임이 명확해야 해요. 모든 클래스가 모든 값을 검증할 필요는 없습니다.

2024-09-13 16:04 UTC, rlawltjd8547 commented on Toy2/src/Calculator.java
> +    private void validateState() {
목적은 파싱의 대한 검증과 계산의 대한 검증은 별개로 생각하였기에
각자의 역할과 책임이 갖추어 졌다고 생각을합니다
하지만 아직 계산기 메인로직의 검증부를 구현을 GPT에 의존하여 했기에
실제로 제 스스로 검증로직을 만들어야할 차례입니다

2024-09-14 02:28 UTC, f-lab-maverick approved these changes
복잡도가 높고, 직접 로직을 작성하지 못한 부분이 아쉽지만 아직 구현력을 키우는 단계라서 여러 미션을 수행하고 다른 코드를 분석하는 작업을 진행하며 키우는게 좋아보입니다.

고생하셨습니다.

2024-09-14 02:28 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +        // 필요한 경우 다른 연산자들도 이곳에 추가 가능
연산이 추가될 때 마다 수동으로 이렇게 추가해주기보다는 enum을 직접 Map으로 변환해주는 방법도 있습니다. 이렇게 해두면 연산자가 추가되어도 다른 코드를 수정할 필요가 없습니다.

```
Arrays.stream(MathSign.values())
      .collect(Collectors.toMap(MathSign::getValue, Function.identity()))
```

2024-09-14 02:28 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +            if (token.equals("(")) {
간단한 기법이지만, equals를 사용할 때에는 절대로 null이 되지 않는 리터럴에서 equals메서드를 시작해주는게 좋습니다. 의외로 이런 부분때문에 NPE가 자주 발생하니 아래와 같이 사용하는 습관을 들여주세요.

```suggestion
            if ("(".equals(token)) {
```

2024-09-14 02:28 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +    private void validateState() {
아직 구현과 관련된 스킬을 좀 더 키워야할 때라서, 현재 후위수직계산식을 구현하기에 어려움이 있을 것으로 보입니다. 현재 GPT를 통해 생성한 코드를 해설하고, 주석을 상세하게 달아줄 수 있다면 우선 AI의 도움을 받은 이 코드를 사용하고 차차 직접 복잡한 비즈니스 로직을 구현할 수 있도록 난이도를 높여가는게 좋겠네요.

2024-09-14 02:28 UTC, f-lab-maverick commented on Toy2/src/Calculator.java
> +    }
Enum을 쓰셨다면, 여기서도 사용할 수 있습니다.
```suggestion
    //연산자 검증을 위한 메소드
    private boolean isOperator(String str) {
        return operations.containsKey(str);
    }
```

2024-09-19 14:34 UTC, merged