#22 [test코드 작성해보기]
f-lab-edu/HS_ToyJava pull request #23
Opened 2024-09-20 08:59 UTC by rlawltjd8547

기본적인 어노테이션을 사용해보는 TestsServiceTest클래스와
Nested를 이용해본 NestedServiceTest클래스를 작성해보았습니다

2024-09-23 13:36 UTC, rlawltjd8547 commented on TestCode/src/main/java/com/example/testcode/stringutil/StringUtil.java
> +    }
해당 구문에서 for문에 if문이 3개가 있는것과
바깥블럭에서 if문 하나 그리고 for문 안에 if문 2개 인 상황에서 성능적인 차이가 있을까요?

for문과 if문의 총갯수는 같지만 어디에있느냐에 따라서도 크게 성능적으로 영향이 있는지 궁금합니다!

2024-09-23 13:36 UTC, rlawltjd8547 commented on TestCode/src/test/java/com/example/testcode/stringutil/StringUtilTest.java
> +    public void givenString_whenSplit_thenSplitedString() {
50번째 라인은 Nested로 나누지 않고 그냥 @Test로 작성했습니다
![image](https://github.com/user-attachments/assets/d67c9fb3-621b-4280-bcfd-1b5b65702046)
결과를 볼때 신기하게 @Nested 어노테이션을 적용한 부분("문자열 뒤집기 테스트입니다")이 코드가 위에있지만
결과창에는 아래에 나오더라구요
아직 잘모르지만 무엇가가 있는것같습니다 @Nested를 안쓰려해봤는데 그냥 한번 또 궁금해서 한번더 적용해버렸습니다..ㅎ

2024-09-23 13:50 UTC, rlawltjd8547 commented on TestCode/src/main/java/com/example/testcode/stringutil/StringUtil.java
> +    }
간단한 메소드를 만들고 질문드려봅니다!
TDD라는것은 테스트 주도 개발이기에 해당 테스트코드를 작성하고
실제 구현메소드에서는 로직구현이아닌 테스트시나리오의 흐름을 위해 그냥 테스트 성공 케이스의 결과값을 반환만 바로하는 형태로 만들고 테스트를 더 진행한뒤 로직구현하는것이 맞는건가요?

또 다른 예로는 
    public static boolean ex(int number) {
        return false; // 임시로 false 반환
    }
해당 형태처럼 실제 구현부에는 미리 결과만 이런식으로 보내놓고 테스트를 작성후 이후 로직 구현 이런 느낌인건가요?

2024-09-23 13:50 UTC, rlawltjd8547 commented on TestCode/src/test/java/com/example/testcode/stringutil/StringUtilTest.java
>      }
테스트에는 다양한 케이스들이 존재할텐데
타입에 따라서, 문자형태에따라서 등등
해당 테스트는 대문자로 변경하는 로직을 위한 테스트인데 뭐 숫자가있는경우의 처리를 한다고하면
해당 메소드를 구현하고 테스트를 할때 
새로운 테스트시나리오를 만드나요? 아니면 해당 블럭에 같이 테스트 케이스 2개가 존재하게되는건가요?
**1. 입력값은 문자만 대문자 변환 2. 입력값의 숫자가있는경우**  이렇게 @test 2개로 나누는지
**1. 입력값은 문자만 대문자 변환 and 입력값의 숫자가있는경우** 이렇게 하나의 테스트코드 블럭에 존재해야하는지 입니다

2024-09-24 13:50 UTC, f-lab-maverick requested changes

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/main/java/com/example/testcode/dateutil/DateForMat.java
> +public class DateForMat {
`DateFormat` 이라는 클래스명을 의도하신듯하지만, `DateForMat`으로 잘못입력되어있네요~

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/main/java/com/example/testcode/stringutil/StringUtil.java
> +    }
네 그런형식으로 진행하셔도 됩니다. TDD에 정답은 없습니다. "이런 방식만 TDD야" 라고 하는 방식이 아니라, 테스트 주도로 개발하면 모두 TDD라고 부릅니다.
이전에도 말씀드렸다싶이 현재는 TDD라는 단어를 잊으셔야 합니다. 테스트코드의 작성이 익숙해지는 것을 목표로 하시고, TDD나 다른 개발방법론은 테스트코드가 익숙해지면 하나씩 적용해 나가는게 좋겠습니다.

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +   장단점이 무엇이있을까?
우선 Nested를 사용하는것 보다 우선시하여야할 것은 테스트 주제별로 테스트 파일을 나누는 것입니다.
하나의 클래스에 Nested로 만드는 것 보다, 큰 주제별로 테스트 파일 자체를 나누어 관리해보세요.

`@Nested`의 경우 하나의 큰 범주 내에서 세부 케이스가 필요할 경우 사용합니다.

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +        class start {
클래스의 네이밍은 첫 글자가 대문자여야 합니다. 네이밍 룰은 가독성을 향상시키기 위해 가장 중요한 부분이기 때문에 꼭 신경써주세요.
자바 네이밍컨벤션은 아래 문서를 참고해주세요.
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +            @DisplayName("덧셈하기")
테스트의 명칭은 [이 테스트가 어떤 조건에서] [어떤 동작을 하는지]가 포함되어야 합니다. 테스트 명칭을 명확하게 지어주서야 이 테스트가 어떤 기능을 테스트하는지, 이 테스트가 실패할 경우 어떤 기능에 문제가 되는지를 파악할 수 있습니다.

이 경우 [덧셈하기] 보다 적절한 네이밍은 [두 정수를 더할 경우 정수의 합을 반환해야 한다] 정도겠네요.

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +        class fail {
실패케이스 테스트의 경우에도 어떤 경우에 테스트를 실패하는지가 명확해야 합니다.
또한 case2 와 같이 표기하기 보다는 조금 길어도 테스트 명에 정확하게 어떤 케이스인지 명시해주는 것이 테스트 실패시 원인 확인을 더 빠르게 만들어줄 수 있습니다.

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +            }
이 테스트의 경우에도 [뺄셈하기] 보다 더 적절한 이름이 있지 않을까요?

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/NestedServiceTest.java
> +            void FirstTest() {
메서드의 명칭 또한 첫 글자가 반드시 소문자여야 합니다.
네이밍 컨벤션 관련 피드백이 계속 발생하는데요, 신경써주시면 좋겠습니다~

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/dateutil/DateForMatTest.java
> +    }
테스트케이스는 동일한 메서드를 사용할 때 최소 세가지는 나와야 합니다.

1. 성공 케이스
2. 실패 케이스
3. 경계 케이스

위 조건을 키워드로 테스트 케이스를 좀 더 짜보시겠어요?

2024-09-24 13:50 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/stringutil/StringUtilTest.java
> +    public void givenString_whenSplit_thenSplitedString() {
테스트코드는 작성한 순서대로 실행되지 않습니다. 
순서를 지정해야 할 경우 [여기](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-methods)를 참고해주세요.

2024-09-25 08:48 UTC, rlawltjd8547 commented on TestCode/src/test/java/com/example/testcode/dateutil/DateForMatTest.java
> +    }
현재로썬 테스트케이스가 나올때
메소드 하나당 3개의 케이스로 생각하면될까요?
그렇게 되면 만약 유틸기능이 3개가있다고하면
테스트는 총 9개를 진행해야되는거구요?

2024-09-25 09:45 UTC, rlawltjd8547 reviewed
경계테스트를 진행할때는
경계테스트가 아직 어떤식으로 초점을 두고 작성을해야할진모르겠습니다
그래도 작성은 진행해보았고
하나 의문점이 든것은 경계테스트같은경우는 성공과다르게 여러케이스가 존재하더라구요 이와
같은 경우는 실패케이스도 있구요
테스트 시나리오가 성공과 다르게 실패,경계 의 경우는 여러 케이스를 작성해야할것같다는 생각이듭니다!

(네이밍 컨벤션은 신경을 계속 쓰고있는데 계속 놓치기도 하고 습관이 무섭다는 생각이 드네요...조금더 천천히 푸쉬 이전에 한번더
검토를 꼼꼼히 하도록하겠습니다!!)

2024-09-25 11:58 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/stringutil/StringUtilTest.java
>      }
동일한 메서드의 입출력에 의해 결과값이 달라진다면 동일레벨로 추가 케이스를 만들어 테스트 작성을 해주시면 되겠습니다.

2024-09-25 12:00 UTC, f-lab-maverick commented on TestCode/src/test/java/com/example/testcode/dateutil/DateForMatTest.java
> +    }
네. 메서드가 세개가 있다면 기능당 세개의 테스트를 만들어보세요.
단위테스트는 원래 메서드 단위로 만드는 것은 아니지만, 현재는 메서드를 단위로 테스트 작성을 연습해본 후 최종적으로는 [가장 작은 비즈니스 로직 단위]를 기준으로 테스트를 작성해주시면 되겠습니다.

보통 가장 작은 단위 := 메서드라서 우선 메서드를 기준으로 작성해주세요.

2024-09-25 12:13 UTC, f-lab-maverick approved these changes
좋습니다~ 이어서 [Parameterized Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests)를 작성해보시죠.

`@ValueSource` / `@EnumSource` / `@MethodSource` / `@FieldSource` / `@CsvSource` / `@ArgumentsSource` 를 사용해보는 것이 목표입니다.

파라미터 테스트는 input값의 범위가 정해져있을 때 유용합니다.
예를 들어, "날짜를 입력 받으면 다음 일요일이 되는 날짜를 찾는" 메서드가 있을 경우 여러 케이스가 있습니다.

이 경우 성공하는 케이스, 실패하는 케이스도 세부 내역으로 나눠지죠.
성공 케이스 예시)
1. 정상케이스 [입력] 2024-09-25 [출력] 2024-09-29
2. 정상케이스 [입력] 2024-09-26 [출력] 2024-09-29
3. 정상케이스 [입력] 2024-09-27 [출력] 2024-09-29
4. 경계값 케이스 [입력] 2024-09-29 [출력] 2024-10-06

실패 케이스 예시)
1. 포맷이 맞지 않음 [입력] 1234
2. 포맷이 맞지 않음 [입력] 1111-11-99
등등..

이렇게 동일한 성공과 실패를 테스트하지만, 여러 파라미터로 테스트할 경우 유용합니다. 파라미터 테스트로 새로운 PR을 만들어 리뷰를 요청해주세요.

이 PR은 머지해주셔도 좋습니다. 고생하셨습니다.

2024-09-25 17:57 UTC, merged