#27 [MyList생성 생성자 만들기]
f-lab-edu/HS_ToyJava pull request #28
Opened 2024-10-15 12:04 UTC by rlawltjd8547

2024-10-18 09:27 UTC, rlawltjd8547 reviewed
이번 PR은 테스트코드도 중요하지만 구현체를 GPT에 의존하지않고 진행하는게 우선적인 목적이였습니다
코드가 진짜 날것 그자체인것같아요 제 눈에도 허점이 너무 많습니다 코드가
아직 진행해야할게 많지만 지금까지 진행한것 까지 피드백 이후로 방향을 다시 잡고 
나머지 진행을 하려합니다!


1. 테스트코드는 성공 테스트만 진행을 우선적으로 했습니다만
   아직 감은 잘안오는데 파라미터 리턴값과 메소드 동작방식이 뭔가 어느 공통적인 형태들은 
   실패케이스가 필요가 없다는 느낌이 들었습니다 (대표적으로는 생성자와 add정도입니다만)
   그리고 무엇보다 예외,실패,경계,파라미터 테스트는 PR이후 진행해보려고 합니다
   메소드 테스트가 성공,실패,경계 중에서 일부만 구현해되는지 전체다 구현해야되는지
   뭔가 감이 오는것같으면서도 제가 잘못생각하고있을것같아서 우선 피드백이 필요한 상황인것 
   같아 피드백이후 테스트를 좀더 진행해보도록할려합니다
   
 2. 구현체는 해당 매소드들이 어떤 동작을 하는지 GPT에게 물어보고 대부분 구현은 제가 직접 
 했습니다 GPT도움을 받기는 했네요 어떤 메소드인지 알고 만들어야해서....
 
 3. 아직 많이 수정해야할것같습니다 만족스럽지 않습니다 예외부분도 더 생각하면 검토할수있는 부분이있을것같고 공통메소드로 더 뺄수있을것같다는 생각이듭니다
 
 4. 테스트에서 진짜 그냥 날것그대로 제가 작성하고싶은대로 작성해봤습니다
    작성을 해보고나서 어 이거 더러운데?...라는생각이 들지만 피드백이후에 
    고쳐볼려고합니다

2024-10-18 12:13 UTC, f-lab-maverick requested changes
고생하셨습니다. 테스트케이스별로 테스트파일을 분리해주신 부분 좋았습니다 👍 
조금 더 보강할 수 있도록 코멘트 남겨두었으니 확인 후 수정해주세요.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
어떤 의도로 만든 생성자인가요? 테스트용이며 사용하지 않는 생성자라면 삭제해주세요. 테스트코드만을 위한 생성자라도 만들지 않는게 좋습니다. 테스트코드는 실제 사용 가능한 부분만 테스트해야 합니다.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
👍 좋습니다.
false가 리턴되는 경우는 없을까요?

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
이러면 실제로 newCapacity의 값은 기존 크기대비 얼마나 늘어날까요?

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
아예 변수를 안쓰고 하는 방법도 있습니다.

```suggestion
    @Override
    public boolean addAll(Collection<? extends E> c) {
        //true/false반환하기위한 플래그 필요
        boolean retrunValue = false;
        //for문 돌때마다 플래그변수 대입되는게 불편...
        // 근데 true에서 또 true대입하게되면 그냥 자바는 무시할까?
        for(E o :c) {
            if(add(o)) {
                return true;
            }
        }

        return false;
    }
```

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
이터레이터는 구현하지 못하셨군요. 어려운 부분이라 현재로써는 넘어가도 좋습니다.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
복사해서 리턴해주는 부분 좋습니다~ 이러면 내 원본 배열이 노출되지 않는다는 장점이 있죠 👍

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +            Object result = new Object[size];
제네릭은 런타임시 타임 이레이징이 되기 떄문에, 생성자호출등은 불가합니다.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +            return (T[]) result;
그래서 이렇게 타입캐스팅을 해주는 방식을 많이 사용합니다~

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +        }
현재 이중 반복문을 사용하는데요, 딱 한번의 반복문으로도 처리가 가능하지 않을까요?
또한 일치하는 엘리먼트를 찾을떄마다 배열을 새로 복사하는데요, 일치하는 모든 엘리먼트를 삭제한 후 딱 한번만 배열을 신규생성하면 더더욱 깔끔한 코드가 될 것으로 보입니다.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +        }
아예 배열을 새로 생성하여 할당하는 방법이 있죠.
위 코드방식은 O(n)이겠지만, 신규 배열을 생성한다면 O(1)입니다.

```suggestion
        
            elementData = new Object[size];
        
```

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +
현재 엘리먼트데이터를 뒤에서부터 역순순회하며 찾으면 되지 않을까요?
현재 방식은 신규 배열을 만들어서 순회하는 방식으로, 꽤나 많은 리소스가 들겠네요.

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListAddTest.java
> +    }
총 6개의 요소를 추가했는데 size가 6이어야 하지 않을까요?

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListAddTest.java
꽤나 상세한 테스트케이스네요~ 좋습니다. 점점 시나리오가 구체적으로 변하는군요~

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListConstructorTest.java
> +    }
이 테스트는 어떤 의도로 생성한것인지 알기 어렵네요. 무엇을 테스트하려고 하신건가요?

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListConstructorTest.java
> +    //실패테스트 경계 테스트가 생각이안난다...
생성자가 실패하기는 어렵죠. 이정도로도 충분합니다 :)

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListFunctionTest.java
> +    }
성공과 실패가 같은 테스트코드로 묶여있네요. 명확하게 성공테스트와 실패테스트는 분리해주세요~

2024-10-18 12:13 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListFunctionTest.java
각 메서드의 실패조건이 있다면 실패케이스와 관련한 테스트코드를 추가해주세요.

2024-10-18 14:50 UTC, rlawltjd8547 commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
구현하려는게 동적리스트이다 보니 add에서 false가나는경우를 생각을 해봤을때
실패케이스가 생각이 정말 안나더라구요
너무 많이 추가해서 메모리 문제말고는...
고정크기라면 IllegalArgumentException 말고는 근데 이건 예외니깐...
false가 되는경우는...진행하면서 좀더 고민해보겠습니다

2024-10-18 14:54 UTC, rlawltjd8547 commented on MyList/src/main/java/com/example/mylist/MyList.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
주석을 잘못 달았네요...
시프트연산 보면서 머릿속에 << (2곱하기) >>(2나누기) 이렇게 그냥 외운상태입니다
int newCapacity = oldCapacity + (oldCapacity >> 1);
그러면 "기존크기" + "2로나눈 기존크기" 이기때문에 1.5배를 의도하였습니다

2024-10-18 14:58 UTC, rlawltjd8547 commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
컬렉션 내부 요소들을 모두 추가해야되기때문에
변수를 선언하고 진행하였습니다
제가 잘못 생각하고있는걸수도있지만
처음에 저도 저렇게 시도하였다가
저렇게 시도하면 컬렉션요소 한번만 체크하고 바로 true가 리턴되니깐 컬렉션 다음 요소를 추가할수없어서
변수를 추가한거였는데...
제가 한번 다시 찾아보겠습니다!

2024-10-18 15:08 UTC, rlawltjd8547 commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
remove는 구현을 못하고 hasNext랑 next는 구현했다고 생각했는데
저게 아닌거였나요?? 헐 다시 한번 해보겠습니다

2024-10-18 15:10 UTC, rlawltjd8547 commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
아..그 의도를 가지고 한건아니였는데
생각하지 못한부분이 있었네요.. 좀더 생각을 하면서 구현을 해야할것같습니다

2024-10-18 16:05 UTC, rlawltjd8547 commented on MyList/src/test/java/com/example/mylist/MyListConstructorTest.java
> +    }
컬렉션객체를 넣어서 생성하는 생성자 테스트였습니다
아 지금 다시 보니 설명이 너무 모호한것같습니다...

2024-10-18 16:07 UTC, rlawltjd8547 commented on MyList/src/test/java/com/example/mylist/MyListFunctionTest.java
> +    }
뭔가 제가 생각했었던거는 시나리오가 비슷한결인것같아서 즉 실패테스트가 특이하지 않은 당연한 케이스인것같아서
한번 묶어보자는 의도로 진행했습니다만
역시 성공,실패 케이스는 분리하는게 맞는것같습니다 ㅎㅎ...

2024-10-19 08:31 UTC, rlawltjd8547 commented on MyList/src/test/java/com/example/mylist/MyListFunctionTest.java
>      }
제가 이런식으로 테스트 코드작성을하고나서
아 이거 이렇게하면 좀 이상한가? 라는 의문을 많이 가졌었습니다
이런식으로 assert문이 많아도 괜찮은건가요?..

2024-10-19 13:57 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
고민해봐서 없다면 억지로 구현하지 않아도 좋습니다~

2024-10-19 14:01 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
아하 그렇네요. 모든 요소를 추가하는것이니 저렇게 리턴하면 문제가 생기겠네요. 잘 캐치해주셨습니다 👍

2024-10-19 14:01 UTC, f-lab-maverick commented on MyList/src/main/java/com/example/mylist/MyList.java
> +    }
remove부분을 말씀드린겁니다 ㅎㅎㅎ 모든 내용을 구현하지 않아도 됩니다.

2024-10-19 14:03 UTC, f-lab-maverick commented on MyList/src/test/java/com/example/mylist/MyListFunctionTest.java
>      }
이렇게 검증할 것이 많은 경우 `assertAll`을 사용해주는게 좋습니다.
검증이 많아도 괜찮습니다~

2024-10-19 14:11 UTC, f-lab-maverick approved these changes
List Collection의 생성은 이정도로 충분해보입니다.
머지해주셔도 좋습니다. 고생하셨습니다~

2024-10-19 14:15 UTC, merged