#6.[사용자에 입력값보관 클래스 생성]/[결과리턴을위한 클래스생성]/[숫자야구 구현을위한 초반기능 설계]/[질문 너무많아서…
f-lab-edu/HS_ToyJava pull request #9
Opened 2024-08-01 10:29 UTC by rlawltjd8547

… 중간 커밋]

2024-08-05 10:09 UTC, f-lab-maverick requested changes
리뷰에 대한 보강을 해주신 뒤 다시 리뷰요청 해주세요~ 고생하셨습니다.

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +                .count();
`.count()` 가 `long` 타입 리터럴을 반환하기 때문에 `IntStream` 을 사용하는것과는 무관합니다.
하지만 저번에도 말씀드렸듯이 `int`가 아닌 `Long`타입을 사용하는 것을 습관적으로 익혀주시는게 좋으므로, `LongStream.range...` 를 사용해주시면 되겠습니다.

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +                .count();
`i -> computerNumbers.get(i).equals(userInput.getUserInput().get(i))` 는 컴퓨터의 특정 순서 숫자와 유저가 입력한 특정 순서 숫자가 일치하는지를 검증합니다. 이 검증이 반복되는데요, 반복되는 코드는 메서드로 빼면 가독성이 증가합니다.

```suggestion
        long strikes = IntStream.range(0, computerNumbers.size())
                .filter(i -> isStrike(i, userInput))
                .count();

        long balls = IntStream.range(0, computerNumbers.size())
                .filter(i -> !isStrike(i, userInput))
                .filter(i -> computerNumbers.contains(userInput.getUserInput().get(i)))
                .count();
         ...
         
             private boolean isStrike(int i, UserInput userInput) {
               return computerNumbers.get(i).equals(userInput.getUserInput().get(i));
             }
```

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +     if MatchResult구현시 GameResult를 상속하면? 스트라이크,볼 타입 공유가 가능하다?
상속은 코드의 공유를 위한 것이 아닙니다.
말씀하신 방법으로 스트라이크와 볼을 공유하는 방법은 지양해주세요. 필요하다면 인터페이스로 공통메서드를 만든 후 인터페이스를 구현하도록 만드는 것은 괜찮습니다.

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +    }
생성자로 strike 개수와 ball 개수를 입력받기 때문에 setter는 불필요하지 않을까요?

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        this.matchCount++;
GameResult 객체는 게임 전체적인 결과를 모두 가지고 있어야 합니다.
따라서 save 메서드를 호출할 때 마다 strikes, balls 상태를 계속 덮어쓰기한다면 이렇게 save하는 방식은 적절하지 않습니다. (이전 게임의 결과를 알 수 없음

GameResult가 MatchRetult 객체를 컬랙션으로 들고있게 만들면 어떨까요? 그렇다면 그 컬랙션에 count() 메서드를 사용함으로서 유저가 몇번의 입력을 했는지도 알 수 있으니 `matchCount` 변수도 필요 없어지겠네요.

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/MatchResult.java
> +    }
기본생성자는 불필요해보입니다~ `strikes`, `balls`은 이 MatchResult 객체를 생성하는 시점에 정해지고 이후로는 변경될 일이 없으니 기본생성자과 setter는 불필요하지 않을까요?

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/MatchResult.java
> +    }
GameResult가 MatchRetult 컬랙션을 가지고
MatchResult에 strike / ball 개수를 가지고있게 만드시면 되겠습니다. 

GameResult에도 strike / ball 개수를 선언하려고 하셔서 혼동이 오시는것 같네요.

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/UserInput.java
> +    }
setter가 필요한가요? 불필요한 setter를 선언한 것은 아닐까요?

2024-08-05 10:09 UTC, f-lab-maverick commented on Toy1/src/main.java
> +                System.out.println("잘못된 입력입니다. 다시 시도하세요.");
UserInput 객체를 미리 선언하지 않으셔도 됩니다. 객체는 필요할 때 생성하는거지 미리 생성해둔 후 setter를 호출하는 방식은 불완전한 상태의 객체를 만드는 것이에요.
만약 setter를 호출하지 않은 상태의 `UserInput` 객체가 있다면, 이 객체 내부에 값이 있는지 없는지 판단할 수 없습니다.

따라서 객체를 생성함과 동시에 초기화를 하여 불완전객체 자체가 존재하지 않도록 해주세요.

```
if (hasUniqueDigits(testcase2)) {
  return new UserInput(new ArrayList<>(testcase2));
}
```

2024-08-18 19:01 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +        this.matchCount++;
생성자로 matchResult를 받아 생성하는행위도 결국은 덮어쓰기하는행위와 같은것 아닌가요??...

2024-08-20 10:31 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        this.matchCount++;
생성자를 만들어 둔 후 setter를 제거하면 그 상태는 변경되는 경로가 없어지므로 불변성이 생깁니다. 이 부분은 멘토링때 "불변객체 다루기" 를 주제로 좀 더 알려드리겠습니다 :)

2024-08-20 10:49 UTC, f-lab-maverick requested changes
오늘 리뷰는 질문 코멘트를 남겨보았습니다. 질문에 대한 답변을 남겨주시고, 오늘 멘토링시간때 좀  더 깊이있게 이야기해보면 좋겠습니다.
고생하셨습니다. 첫 완성이 곧 머지않았네요.

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +    public void setComputerNumbers(ArrayList<Long> computerNumbers) {
여기는 왜 인터페이스에서 `ArrayList` 타입으로 변경하신건가요? 변경한 이유가 있으신가요?

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +
현재 구조는 `GameResult`가 가장 마지막으로 진행된 결과(`MatchResult`)를 하나만 들고있는 형태네요.
사용자의 모든 게임 결과를 저장할 수 있도록 하려면 어떻게 변경해야할까요?

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +    final static Scanner scanner = new Scanner(System.in);
전역변수를 사용해도 좋습니다.
다만, 전역변수를 지양하라는 말이 있는 이유는 전역으로 변수를 사용했을 경우 여러 고려사항이 필요한데 이걸 고려하지 않는 경우가 많아서 그런것입니다.

대표적으로 상수가 아닌 변수를 전역으로 선언할 경우 여러 스레드에서 동시에 전역변수에 접근하려 하기 때문에 동시성 이슈가 발생할 수 있습니다

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +            gameResult.save(Result);
이미 `Result`를 생성자로 넘겨주었기 떄문에 save를 호출할 필요가 없어보이네요.

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +              어 toArrayList는없다? 그러면 toList로만 변환하는게 맞는건가?
`Stream.collect`를 사용하면 ArrayList로 변환이 가능합니다. 다만 사용방법이 어렵기 때문에, 쉽게 하시려면 일단 `toList`로 뽑아낸 후 ArrayList로 옮겨담는 방식을 사용할 수도 있습니다.

근본적으로 List의 구현체가 중요한 상황이라면 구현이 잘못되었을 가능성이 높습니다. 왜 꼭 ArrayList가 필요하다고 생각하셨나요?

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +    }
👍

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +    }
👍 

조금 더 개선한다면 List가 아닌 Set으로 입력받는다면 애초에 중복이 존재하지 않겠죠?

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/main.java
> +                            .collect(Collectors.toCollection(ArrayList::new));
왜 ArrayList로 Collect 하셨나요? 이 구현체를 사용한 이유가 있으신가요?

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +        return computerNumbers.get(i).equals(userInput.getUserInput().get(i));
👍  메서드 분리가 점점 익숙해지시네요~ 좋습니다.

2024-08-20 10:49 UTC, f-lab-maverick commented on Toy1/src/MatchResult.java
> +    private long matchCount = 0;
`matchCount`는 어떤 역할을 하나요?

2024-08-20 10:54 UTC, rlawltjd8547 commented on Toy1/src/ComputerNumbers.java
> +    public void setComputerNumbers(ArrayList<Long> computerNumbers) {
private final ArrayList<Long> computerNumbers;
해당 변수에 직접적인 영향을 주는 코드라고 생각해서
List가아닌 명확히하기위해 ArrayList로 다시 변경하였습니다!

2024-08-20 10:59 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +
저도 의문을 가졌던 부분인것같습니다
GameResult가 MatchResult하나만들고있기에는 역할도 너무 이상한것같았습니다
만약 말씀해주신 모든게임의 결과를 알수있도록 이라는 가정이 생기면
GameResult의 명확한역할도 새로 생기게 되는거같습니다
지금 생각나는것은 
해당 클래스의 Map을 하나 만들어서 Key= 시도 횟수 , value는 스트라이크 아웃 카운트 를 저장하게끔
Map변수와 행위 메소드 하나를 만들면 될것같다는 생각이 듭니다

2024-08-20 11:01 UTC, rlawltjd8547 commented on Toy1/src/main.java
> +              어 toArrayList는없다? 그러면 toList로만 변환하는게 맞는건가?
ArrayList를 사용한이유는 딱히 없습니다 일할때 기계마냥 List? 그냥 ArrayList쓰자~~!
라는 무의식에 그런것같습니다....

2024-08-20 11:12 UTC, rlawltjd8547 commented on Toy1/src/main.java
> +    }
난수생성한 ComputerNumber는 List여서 Set으로 받게되면 후에 값을 비교하는 작업에서
컨버팅이 필요할것같아서 피해보려고 동일한 컬렉션을 사용하려고 했습니다
long strikes = IntStream.range(0, computerNumbers.size())
                .filter(i -> isStrike(i, userInput))
                .count();
스트림과 컨버팅 관계를 잘몰라서 이부분은 좀더 찾아봐야할것같습니다!
물론 제가 잘 몰라서 동일하게 만들자! 라는 생각이 강하기도 했구요

2024-08-20 11:15 UTC, rlawltjd8547 commented on Toy1/src/main.java
> +                            .collect(Collectors.toCollection(ArrayList::new));
ArrayList<Long> userInput;
userInput역시도 명확한 값이다보니 ArrayList로 선언하였고 그에따라 ArrayList로 받고 넣어줄려는 의도였습니다
대부분은 List로 써야할것같은데 이게 변수만 ArrayList로선언하고 해당변수를 타 메소드에서 다룰때 List를 써야할지 
ArrayList를 써야할지 아직 헷갈립니다...

2024-08-20 11:17 UTC, rlawltjd8547 commented on Toy1/src/MatchResult.java
> +    private long matchCount = 0;
이 MatchCount를 어떻게 만들어야할지 모르는 부분입니다!
10번이상은 실패 조건을 위해 만들어진 변수인데 
좀더 좋은방법으로 기능을 만들수있을것같은데
어떻게 만들어야할지 모르겠습니다......

2024-08-21 15:25 UTC, rlawltjd8547 reviewed
완성할줄 알았는데 생각치못한 초기화와 생성자 문제를 접하였다..

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
Map을 추가함으로써 고려할것이 많아졌습니다 
초기화 시점과 생성자 2가지가 좀 많이 고민을 했습니다

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/main.java
> +
기존에는 while문 안에서 GameResult를 생성했는데 이러다보니
Map이 자꾸 초기화가 되서 아 외부로 뺴야하는건가 라는 생각을 했는데
이러면 아직 게임결과가 없는시점에서 GameResult를 기본생성자로 만들어야하나라는 생각을 했습니다
근데 그러면 안되니싼 우선 MatchResult는 의미없는 0,0으로 만들어서 최초 생성을 했습니다
그렇게 좋은 코드는 아니네요 뭔가 제가 놓치고있거나 생각을 못하고있는것같습니다

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/main.java
셔플을 사용하니 생각치도 못한 이슈가 나왔습니다 ㅋㅋㅋ
자바 16버전이상부터 toList가 불변리스트로 반환한다 하더라구요
그러면 전에 이야기하신 shuffle의 사용보다는 generate가 무한 순회를할 가능성이 아주 조금 있지만
지금 이 이슈가 나는바에는 generate를 사용함이 좀더 좋은 방법이라고 개인적으로 생각합니다

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
결국 Map에 1~10번째 순서를 알기위해 Key를 넣기위한 숫자 혹은 관리할 변수가 필요하다고 생각했습니다만
뭔가 만들어 놓고 찜찜합니다
그래도 GameResult의 게임의 순서를 알기위한 상태값이라고 생각하면 적절한 변수선언같다고 생각합니다!
static은 초기화 문제를 해결하고나서 다시 지웠습니다!

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +
처음에는 변수에서 초기화를 안하려고했습니다
클래스가 생성될때 초기화를 하려그랬는데 좀 까다로워져서 이렇게했습니다
변수선언후 바로 초기화 하는것과 클래스생성자를 통해서 생성할때 변수 초기화를 하는것중
뭐가 더 나은 방법인지 판단이 어려워서 우선은 동작이 되게끔을 목표로 이렇게 했습니다

2024-08-21 15:25 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
main부분을 같이보면 좋을텐데
처음 생각했었던건 main 에서 while문안에 생성을 이제 바깥으로 빼려했으나
문제가 while문안에서 MatchResult의 결과를 매번 다시 GameResult안에 넣어야해서
생성자를 어떻게 해결해야하는지의 고민을 좀 오래 했습니다만 속시원한 방법을 못찾았습니다

캡슐화를 한 클래스의 생성자 만들기? 불안정한상태를 만들지 않으려면 내부 상태값들을 온전히 다 넣어줄수있을때
생성을 해야하는거같은데 
어떻게 설명해야할지도 솔직히 살짝 감이 안옵니다...ㅠㅠ

2024-08-21 15:28 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +        this.matchResult = matchResult;
main부분을 같이보면 좋을텐데
처음 생각했었던건 main 에서 while문안에 생성을 이제 바깥으로 빼려했으나
문제가 while문안에서 MatchResult의 결과를 매번 다시 GameResult안에 넣어야해서
생성자를 어떻게 해결해야하는지의 고민을 좀 오래 했습니다만 속시원한 방법을 못찾았습니다

캡슐화를 한 클래스의 생성자 만들기? 불안정한상태를 만들지 않으려면 내부 상태값들을 온전히 다 넣어줄수있을때
생성을 해야하는거같은데
어떻게 설명해야할지도 솔직히 살짝 감이 안옵니다...ㅠㅠ

2024-08-21 15:32 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +        this.matchResult = matchResult;
main부분을 같이보면 좋을텐데
처음 생각했었던건 main 에서 while문안에 생성을 이제 바깥으로 빼려했으나
문제가 while문안에서 MatchResult의 결과를 매번 다시 GameResult안에 넣어야해서
생성자를 어떻게 해결해야하는지의 고민을 좀 오래 했습니다만 속시원한 방법을 못찾았습니다

캡슐화를 한 클래스의 생성자 만들기? 불안정한상태를 만들지 않으려면 내부 상태값들을 온전히 다 넣어줄수있을때
생성을 해야하는거같은데
어떻게 설명해야할지도 솔직히 살짝 감이 안옵니다...ㅠㅠ

2024-08-21 15:32 UTC, rlawltjd8547 commented on Toy1/src/main.java
>              System.out.println(gameResult.formatLastGameResult());
기존에는 while문 안에서 GameResult를 생성했는데 이러다보니
Map이 자꾸 초기화가 되서 아 외부로 뺴야하는건가 라는 생각을 했는데
이러면 아직 게임결과가 없는시점에서 GameResult를 기본생성자로 만들어야하나라는 생각을 했습니다
근데 그러면 안되니싼 우선 MatchResult는 의미없는 0,0으로 만들어서 최초 생성을 했습니다
그렇게 좋은 코드는 아니네요 뭔가 제가 놓치고있거나 생각을 못하고있는것같습니다

2024-08-21 15:32 UTC, rlawltjd8547 commented on Toy1/src/main.java
>          return new ComputerNumbers(testcase1);
셔플을 사용하니 생각치도 못한 이슈가 나왔습니다 ㅋㅋㅋ
자바 16버전이상부터 toList가 불변리스트로 반환한다 하더라구요
그러면 전에 이야기하신 shuffle의 사용보다는 generate가 무한 순회를할 가능성이 아주 조금 있지만
지금 이 이슈가 나는바에는 generate를 사용함이 좀더 좋은 방법이라고 개인적으로 생각합니다

2024-08-22 10:40 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +
이런 방식도 좋습니다~
객체 생성에 필수적으로, 그리고 같은 값으로 초기화되는 값(컬랙션 등)은 생성자로 초기화하는것보다는 변수 선언과 동시에 초기화해주는게 좋습니다.
final 키워드를 통해 변수 재할당을 막는다면 더더욱 좋겠죠?

2024-08-22 10:44 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        this.matchResult = matchResult;
### 네이밍 컨벤션
메서드 이름을 바꿔보면 좋겠네요. 변수를 입력한다는 것을 관습적으로 setter 네이밍인 `setXXX`로 이름짓는 경우가 많은데요, 비즈니스로직은 "게임 결과 저장"  입니다.
아래 메서드명으로 지어본다면 setter아 아니니 더 동작이 명확해집니다.

`saveResult` / `save` / `addResult` 등...

### setter?
matchResultMap  내부에 저장해야하는데 setter를 호출할 필요가 있을까요?
아래와 같은 코드는 어떠신가요?
```
public void addResult(MatchResult matchResult) {
  final long gameCount = matchResultMap.keySet().size() + 1;
  this.matchResultMap.put(gameCount, matchResult);
}
```

2024-08-22 10:45 UTC, f-lab-maverick commented on Toy1/src/main.java
>              System.out.println(gameResult.formatLastGameResult());
GameResult는 전체 게임의 결과를 저장하는곳이죠.
지금 만드신 생성자는 게임 결과를 입력해야 하는 생성자입니다. 게임을 시작하지도 않았는데 결과를 먼저 입력할 수는 없겠죠.

이 경우에는 GameResult에 생성자 파라미터를 빼서 기본생성자로만 생성하게 만드는게 더 적절해보입니다.

2024-08-22 10:46 UTC, f-lab-maverick commented on Toy1/src/main.java
>          return new ComputerNumbers(testcase1);
네 불변 리스트라면 이런 방식으로 하는것도 좋네요~

2024-08-22 10:50 UTC, f-lab-maverick requested changes

2024-08-22 10:50 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +        if(computerNumbers.stream().distinct().count() != 3){
이번에는 매직넘버라는 개념을 제거해봅시다.
컴퓨터 넘버의 자리수가 3인지를 검증하는데, 이 3이라는 숫자는 반복적으로 등장합니다.

그렇다면 이 숫자를 상수화해서 어딘가 보관한다면 더 관리가 명확하고, 해당 숫자에 이름도 붙여주어 어떤 역할을 하는지도 말해줄 수 있겠네요.

매직넘버란 소스코드에서 변수에 담기지 않은 상태로 하드코딩된 리터럴을 의미합니다. 이번에는 이런 날것의 값들을 모두 상수로 변경해보세요.

2024-08-22 10:50 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +    }
setMatchResult는 불필요하겠네요. 애초에 matchResult를 담는 `matchResultMap` 이 있기 떄문에 GameResult 클래스는  `private MatchResult matchResult` 변수를 가질 필요가 없습니다.

2024-08-22 10:50 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        return matchResult.getStrikes() == 3 || gameCount == 10;
여기도 매직넘버가 있네요~ 상수로 변경해보세요.

2024-08-22 10:50 UTC, f-lab-maverick commented on Toy1/src/UserInput.java
> +    }
여기도 입력받은 리스트를 복사해서 세팅해주는게 좋겠네요. 입력받은 리스트를 그대로 상태로 들고있으면 객체에서 아무 작업을 하지 않아도 외부의 영향을 받아 내부 리스트 상태가 변경될 수 있습니다.

2024-08-22 12:26 UTC, rlawltjd8547 commented on Toy1/src/GameResult.java
> +        this.matchResult = matchResult;
와...간단한건데 이코드보고 기가막혔습니다...wow...

2024-08-23 09:43 UTC, f-lab-maverick requested changes

2024-08-23 09:43 UTC, f-lab-maverick commented on Toy1/src/ComputerNumbers.java
> +            throw new IllegalArgumentException("컴퓨터 숫자는 "+ Constants.THREE +" 자리수여야합니다.");
상수화는 하셨지만 의미부여는 실패하셨군요.
3이라는 숫자 그 자체를 상수화하는것보다는, 이 값에 있는 비즈니스로직의 명칭을 지정해주는게 좋습니다.

예를 든 변수값이라면 `COMPUTER_INPUT_NUMBER_LENGTH` 와 같은 이름이 있겠네요.
기계적으로 3이라는 숫자를 상수에 담아야하니 `THREE`라는 이름으로 만드는건 상수화의 장점을 가져가기 어렵습니다.
`COMPUTER_INPUT_NUMBER_LENGTH` 와 같은 값에 상수를 담았다면 추후 비즈니스로직이 바뀌어 4자리수를 받는다면 저 숫자만 바꿔주면 되지만, `THREE` 상수를 쓰는곳은 모든 사용처를 찾아다니며 상수를 모두 `FOUR`로 바꿔줘야하니까요.

2024-08-23 09:43 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        this.matchResult = matchResult;
GameResult내부에 `matchResult `변수를 빼보세요. `matchResultMap` 이 있는데 `matchResult`변수를 추가로 들고있을 이유가 없어보입니다.

2024-08-23 09:43 UTC, f-lab-maverick commented on Toy1/src/GameResult.java
> +        if (matchResult.getStrikes() == Constants.THREE) {
이것도 별도 비즈니스로직인 "게임 종료 스트라이크 개수"니까 이름을 `GOAL_STRIKE_COUNT` / `WINNING_STRIKE_COUNT ` / `TARGET_STRIKES` 등의 이름을 사용할 수 있겠네요.

2024-08-25 00:26 UTC, f-lab-maverick approved these changes
고생하셨습니다. 머지해주셔도 좋습니다 :)

2024-08-25 00:26 UTC, f-lab-maverick commented on Toy1/src/Constants.java
> +    public static final long MAX_GAME_TRY = 10;
👍

2024-08-25 13:07 UTC, merged